### ISSUE TITLE
runtime error in aarch64

### ISSUE THREAD

**Issue by dokoma** [rswinkle/sdl_img#1]
Hi! I like your project , and  I compiled it to aarch64 linux for handheld 

but when it runs, I got 
*** stack smashing detected ***: terminated.

do your have and clue?

any input would be appreciated!

**Comment by rswinkle** [comment]
Thanks, glad someone is using it even though I'm terrible about updates and official releases.

Did you figure out what the issue was?  It's been a while since I compiled and run it on an ARM chip but I have done it and I don't remember any issues.

**Comment by dokoma** [comment]
Oh.. I am so sorry I thought it's been closed by mysellf last week.  I think it's because I set dependency library with even another libc/libm or some basic ones in the LD_LIBRARY_PATH in higher search priority.  Now it works! I'll learn to use it, Thanks for your great work!

**Comment by rswinkle** [comment]
You did close it but you can't just tell someone there's a bug in their program and then disappear without saying anything, haha.  I had to know if there really was a bug or not so I reopened it.

I'm glad you figured it out and that it wasn't a problem with sdl_img.  I did update the Building instructions in the README last week in case you missed it.  I should probably just delete those old build scripts.

Good luck!
